apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app-deployment
spec:
  selector:
    matchLabels:
      app: vote-app
  template:
    metadata:
      labels:
        app: vote-app
    spec:
      containers:
      - name: vote-app
        image: kodekloud/examplevotingapp_vote:v1
        resources:
          requests:
            memory: "64Mi" 
            cpu: "100m"    
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: redis-endpoint

