apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: dockersamples/examplevotingapp_worker
        resources:
          requests:
            memory: "64Mi" 
            cpu: "100m"    
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: postgres-endpoint
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secret-postgres
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-postgres
              key: password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: postgres-db
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: redis-endpoint
        
