name: Despliegue de la configuración del clúster de Kubernetes
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Entorno a desplegar"
        required: true
        type: choice
        options:
        - test
        - production
        default: "test"
  push:
    branches: [ main ]
    paths: [ "kubernetes/**" ]

jobs:
  deploy-application: 
    name: "Desplegar en Entorno ${{ github.event.inputs.environment || 'test' }}"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v5.0.0

      - name: "Azure login"
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: "Set AKS Context"
        uses: azure/aks-set-context@v4
        with:
          resource-group: 'rg-voteapp-dev-fr'
          cluster-name: 'aks-voteapp-dev-fr'

      - name: "Setup Helm & Deploy Ingress Controller"
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
            --namespace ingress-controller --create-namespace \
            --wait

      - name: "Validate Application Manifests (Dry run)"
        working-directory: ./kubernetes/overlay
        run: kubectl -k ${{ github.event.inputs.environment || "test"}} --dry-run=server

      - name: "Deploy Application"
        working-directory: ./kubernetes/overlay
        run: kubectl apply -k ${{ github.event.inputs.environment || "test"}}

      - name: "Verify Deployment Rollout"
        run: |
          kubectl rollout status deployment/vote-app-deployment --timeout=2m
          kubectl rollout status deployment/result-deployment --timeout=2m
          kubectl rollout status deployment/redis-deployment --timeout=2m
          kubectl rollout status deployment/worker-deployment --timeout=2m
          kubectl rollout status deployment/postgres-deployment --timeout=2m
    
